version: '3.8'

services:
  #-------MYSQL-------
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: words
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  #-------PROJECT_FILES-------
  php:
    container_name: php
    hostname: docker
    build:
      context: php
    ports:
      - '9002:9002'
    expose:
      - 9000
    volumes:
      - ../project:/var/www/words/
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - mysql_db
  #-------NGINX-------
  nginx:
    container_name: nginx
    hostname: docker
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - ../project:/var/www/words/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql_db
